### ISSUE TITLE
distributionMediaTimingType does not allow fractions with less then 3 digits

### ISSUE THREAD

**Issue by andreastai** [ebu/ebu-tt-d-xsd#2]
The distributionMediaTimingType currently does not allow the specification of fractions of a second with less than three digits (e.g. 00:00:00.12 would not be allowed). But the EBU-TT-D spec does not specify this restriction.

**Comment by charlesritchea** [comment]
I agree. I was hoping to use this XSD as a validator, but all begin/end tags in the _Elephant's Dream_ sample from here http://rdmedia.bbc.co.uk/dash/ondemand/elephants_dream/1/elephantsdream_25fps.ebuttd.xml fail validation because of this. I would think deciseconds, centiseconds, and milliseconds should all be supported.

**Comment by nigelmegitt** [comment]
@novaterata this should have been fixed now - do you want to review and confirm?

**Comment by andreastai** [comment]
Fixed in commit 87ef5cf6de8a2c2075ecad01771823cadbeedd2a. Please re-open if there is still an issue.

**Comment by charlesritchea** [comment]
Fixed on my end, thanks!
