### ISSUE TITLE
Conflict with TTML1 XSD

### ISSUE THREAD

**Issue by palemieux** [ebu/ebu-tt-d-xsd#5]
ebutt_d.xsd specifies `http://www.w3.org/ns/ttml` as the target namespace, conflicting with the TTML1 XSD -- specifically ttaf1-dfxp-document.xsd, which also defines the same target namespace.

**Comment by andreastai** [comment]
The EBU-TT-D XML Schema is not a complementary schema to the one provided by the W3C. It replaces the W3C Schema for EBU-TT documents because only a subset of the TTML 1 content model is supported. Because the restrictions apply to the same content elements as in TTML 1 the XSD of EBU-TT-D has to define the same target namespace.

**Comment by andreastai** [comment]
Please let me know if this answers your question so I can close the issue.

**Comment by palemieux** [comment]
For convenience I recommend creating a single XSD that imports all EBU-TT-D XSDs then.
